In [1]:
## numpy, pandas
## matplotlib and seaborn

In [2]:
## Numpy
# !pip install numpy    

In [3]:
### import the numpy package
import numpy as np

In [4]:
# len(dir(np))

In [5]:
### Main datastructure
# NDarray - Array

#### properties of list
    - ordered, inxdeable, heterogenous data type
    - mutable
    - duplicate members allowed
    
#### properties of array
    - ordered, inxdeable, homogenous data type
    - mutable
    - duplicate members allowed    

In [6]:
list1 = [1,2,3,4,5]
print(type(list1))
list1

In [7]:
arr = np.array(list1)
print(type(arr))
arr

In [8]:
list1 = [1,2,3,4,5,6.0]
print(type(list1))
list1

<class 'list'>


[1, 2, 3, 4, 5, 6.0]

In [9]:
print(type(list1[-1]))
print(type(list1[-2]))

<class 'float'>
<class 'int'>


In [10]:
arr = np.array(list1) # list of mix data type
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1., 2., 3., 4., 5., 6.])

In [11]:
list1 = [1,2,3,4,5,6.0,'7']
print(type(list1))
list1

<class 'list'>


[1, 2, 3, 4, 5, 6.0, '7']

In [12]:
arr = np.array(list1) # list of mix data type
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['1', '2', '3', '4', '5', '6.0', '7'], dtype='<U32')

In [13]:
# str <- float <- int

In [14]:
list1 = [1,2,3,4,5,6.0,'7',[1,2,3,4]]
print(type(list1))
list1

<class 'list'>


[1, 2, 3, 4, 5, 6.0, '7', [1, 2, 3, 4]]

In [15]:
arr = np.array(list1) # list of mix data type
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6.0, '7', list([1, 2, 3, 4])], dtype=object)

## creating an array

In [16]:
# using np.empty()
arr = np.empty(5) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([5.11798224e-307, 1.37961370e-306, 1.42413555e-306, 2.11392033e-307,
       1.69117157e-306])

In [17]:
# using np.empty()
arr = np.empty((2,5)) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# # using np.empty()
# arr = np.empty((2,5,3)) 
# print(type(arr))
# arr

In [19]:
# using np.empty()
arr = np.empty((2,5),int) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[7602278, 5701724, 7209065, 7274596, 7536759],
       [7340097, 7536752, 4390971, 6029370, 7536725]])

In [20]:
# using np.ones()
arr = np.ones(5) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1., 1., 1., 1., 1.])

In [21]:
# using np.ones()
arr = np.ones((5,2)) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
# using np.zeros()
arr = np.zeros(8) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# using np.zeros()
arr = np.zeros((4,2)) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
# using np.linspace() # always will return 1D Array
arr = np.linspace(start = 0, stop = 10)  # num -> length of the array  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
# using np.linspace() # always will return 1D Array
arr = np.linspace(start = 0, stop = 10, num = 10)     # interval = (stop - start)+1/lenght
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
[0,1,2,3,4,5,6,7,8,9,10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
# using np.linspace() # always will return 1D Array
arr = np.linspace(start = 0, stop = 10, num = 10, endpoint = False) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
# using np.arange() # always will return 1D Array
arr = np.arange(0,10,2)    # lenght = (stop - start)+1/interval
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 2, 4, 6, 8])

In [29]:
arr = np.arange(0,10,3)    
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 3, 6, 9])

In [30]:
arr = np.arange(0,10,0.5)    
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [31]:
## using np.random
arr = np.random.randint(5)    
print(type(arr))
arr

<class 'int'>


3

In [32]:
arr = np.random.randint(5, size = 4)    
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0, 2, 2, 1])

In [33]:
arr = np.random.randint(4,15, size = (4,2))    
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[10,  8],
       [ 8, 10],
       [14, 11],
       [ 6,  5]])

In [34]:
arr = np.random.rand(4)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0.49408534, 0.39417243, 0.53829435, 0.6197546 ])

In [35]:
arr = np.random.rand(4,2)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.14213318, 0.60495831],
       [0.68520134, 0.71760643],
       [0.36283652, 0.44621839],
       [0.78550622, 0.57454217]])

## Accessing Elements

In [36]:
arr = np.random.rand(4)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0.75592145, 0.97401016, 0.32655572, 0.61262299])

In [37]:
print(arr[1])
print(arr[0])
print(arr[-1])
print(arr[0:2])

0.9740101637753277
0.755921450145751
0.6126229882184969
[0.75592145 0.97401016]


In [38]:
arr = np.random.rand(4,2)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.67865926, 0.26705063],
       [0.63241951, 0.27507674],
       [0.38603003, 0.80702378],
       [0.97507809, 0.50488151]])

In [39]:
print(arr[0][0])
print(arr[1][0])

0.6786592584341313
0.6324195113446643


In [40]:
print(arr[0,0])
print(arr[3][-1])
print(arr[3,1])

0.6786592584341313
0.5048815094019595
0.5048815094019595


#### arr[i][j] ~ arr[i,j]

#### Modifying the value

In [41]:
arr

array([[0.67865926, 0.26705063],
       [0.63241951, 0.27507674],
       [0.38603003, 0.80702378],
       [0.97507809, 0.50488151]])

In [42]:
arr[3,1] = 5

In [43]:
arr

array([[0.67865926, 0.26705063],
       [0.63241951, 0.27507674],
       [0.38603003, 0.80702378],
       [0.97507809, 5.        ]])

## Operations on array object

In [44]:
mylist = list(range(1,11))
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
### Add a value '2' to each of the element in the sequence above.
[x+2 for x in mylist]

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [46]:
# mylist + 2 # error

In [47]:
arr = np.array(mylist)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
mylist*2  # duplicate sets will be created

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [50]:
arr*2 # element wise multiplication

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr * arr # elemt wise multiplication

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
arr = np.random.rand(4,2)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.65715046, 0.46812625],
       [0.27971095, 0.02698329],
       [0.67114752, 0.1085078 ],
       [0.89774323, 0.25836157]])

In [53]:
arr * arr

array([[4.31846723e-01, 2.19142187e-01],
       [7.82382144e-02, 7.28098087e-04],
       [4.50438987e-01, 1.17739434e-02],
       [8.05942908e-01, 6.67506995e-02]])

In [54]:
arr * 2

array([[1.31430091, 0.9362525 ],
       [0.5594219 , 0.05396659],
       [1.34229503, 0.21701561],
       [1.79548646, 0.51672313]])

In [55]:
arr ** 2

array([[4.31846723e-01, 2.19142187e-01],
       [7.82382144e-02, 7.28098087e-04],
       [4.50438987e-01, 1.17739434e-02],
       [8.05942908e-01, 6.67506995e-02]])

In [56]:
arr/5

array([[0.13143009, 0.09362525],
       [0.05594219, 0.00539666],
       [0.1342295 , 0.02170156],
       [0.17954865, 0.05167231]])

In [57]:
arr%2

array([[0.65715046, 0.46812625],
       [0.27971095, 0.02698329],
       [0.67114752, 0.1085078 ],
       [0.89774323, 0.25836157]])

In [58]:
### np.mean(),np.sum(),np.max(),np.min(),np.dot(),np.std(),np.reshape(),np.argmax(), np.argmin(), etc.

In [59]:
arr = np.array([2,3,5,1,8,19])

In [60]:
arr.argmax()

5

In [61]:
arr.max()

19

In [62]:
arr = np.random.rand(4,2)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0.03894325, 0.33534489],
       [0.27528569, 0.94113501],
       [0.90397468, 0.79636602],
       [0.4524218 , 0.12150877]])

In [63]:
np.reshape(arr,(8,1))

array([[0.03894325],
       [0.33534489],
       [0.27528569],
       [0.94113501],
       [0.90397468],
       [0.79636602],
       [0.4524218 ],
       [0.12150877]])

In [64]:
arr.reshape((8,1))

array([[0.03894325],
       [0.33534489],
       [0.27528569],
       [0.94113501],
       [0.90397468],
       [0.79636602],
       [0.4524218 ],
       [0.12150877]])

In [65]:
arr = np.random.rand(12)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0.02200914, 0.43417479, 0.77312135, 0.78686241, 0.53766963,
       0.18507621, 0.15277205, 0.01994405, 0.01344205, 0.3502182 ,
       0.02320482, 0.38055299])

In [66]:
arr.reshape((3,4))

array([[0.02200914, 0.43417479, 0.77312135, 0.78686241],
       [0.53766963, 0.18507621, 0.15277205, 0.01994405],
       [0.01344205, 0.3502182 , 0.02320482, 0.38055299]])

In [67]:
arr.reshape((6,2))

array([[0.02200914, 0.43417479],
       [0.77312135, 0.78686241],
       [0.53766963, 0.18507621],
       [0.15277205, 0.01994405],
       [0.01344205, 0.3502182 ],
       [0.02320482, 0.38055299]])

In [68]:
### matrix multiplication - use np.dot()
# NOte: * is used only for element-wise multiplication

In [69]:
arr1 = np.array(range(1,11)).reshape((5,2))
arr2 = np.array(range(1,11)).reshape((2,5))
arr3 = np.array(range(1,11))
arr4 = np.array(range(1,12))
arr5 = np.array(range(11,21))

In [70]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11]
[11 12 13 14 15 16 17 18 19 20]


In [71]:
### 
print('arr3*arr5:\n ',arr3*arr5) # element -wise multiplication (10), (10)
# print('arr3*arr4:\n ',arr3*arr4) # dimension mismatch (10), (11)
# print('arr3*arr1:\n ',arr3*arr1) # dimension mismatch (10), (5,2)
# print('arr1*arr2:\n ',arr1*arr2) # dimension mismatch (5,2), (2,5)
print('arr1.dot(arr2):\n ',arr1.dot(arr2)) # number of columns of the 1st matrix ~ #rows in 2nd matrix

arr3*arr5:
  [ 11  24  39  56  75  96 119 144 171 200]
arr1.dot(arr2):
  [[ 13  16  19  22  25]
 [ 27  34  41  48  55]
 [ 41  52  63  74  85]
 [ 55  70  85 100 115]
 [ 69  88 107 126 145]]


In [72]:
# arr1

In [73]:
# arr2

In [74]:
# 1*1+2*6 = 13

In [75]:
# dir(np)

# Pandas Package

In [76]:
# !pip install pandas

In [77]:
import pandas as pd

#### Main structures 
    - series
    - dataframe

In [78]:
mylist = list(range(1,11))

In [79]:
print(type(pd.Series()))
pd.Series()

<class 'pandas.core.series.Series'>


C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.
C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Series([], dtype: float64)

In [80]:
s = pd.Series(data = range(1,11))
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [81]:
s = pd.Series(data = range(1,11), index = [2,3,4,5,6,7,8,9,1,10])
s

2      1
3      2
4      3
5      4
6      5
7      6
8      7
9      8
1      9
10    10
dtype: int64

In [82]:
s = pd.Series(data = range(1,11), index = list('abcdefghij'))
s

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [83]:
s = pd.Series(data = range(1,11), index = list('aacdefghij'))
s

a     1
a     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [84]:
s = pd.Series(data = range(1,11), index = list('aacdefghij'), dtype='float', name='S_Float')
s

a     1.0
a     2.0
c     3.0
d     4.0
e     5.0
f     6.0
g     7.0
h     8.0
i     9.0
j    10.0
Name: S_Float, dtype: float64

In [85]:
## using list of integer type
s = pd.Series(data = [10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [86]:
## using list of float type
s = pd.Series(data = [10.0,20,30,40])
s

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64

In [87]:
## using list of object type
s = pd.Series(data = [10.0,20,30,40,'50'])
s

0    10
1    20
2    30
3    40
4    50
dtype: object

In [88]:
## using array
s = pd.Series(data = np.array([10.0,20,30,40,'50']))
s

0    10.0
1      20
2      30
3      40
4      50
dtype: object

In [89]:
## using dictionary
s = pd.Series(data = {'a':1,'b':2,'c':4})
s

a    1
b    2
c    4
dtype: int64

In [90]:
## using dictionary
s = pd.Series(data = {'a':[1,2,3],'b':['a','b','b'],'c':[1,4,5]})
s

a    [1, 2, 3]
b    [a, b, b]
c    [1, 4, 5]
dtype: object

In [91]:
## using scalar
s = pd.Series(data = 4)
s

0    4
dtype: int64

In [92]:
## using scalar
s = pd.Series(data = 4, index = range(1,6))
s

1    4
2    4
3    4
4    4
5    4
dtype: int64

### Accessing elements of a series

In [93]:
s = pd.Series(data = range(1,11))
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [94]:
# fetch 1st value 
print(s[0])
print(s[2:6]) # end is exlcuded
# print(s[-1])

1
2    3
3    4
4    5
5    6
dtype: int64


In [95]:
s = pd.Series(data = range(1,11), index = list('abcdefghij'))
s

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [96]:
### fetch 1st element
print(s[0])
print(s['a'])

### fetch last element
print(s[9])
print(s['j'])

1
1
10
10


In [97]:
### fetch 1 to 4
print(s[0:4]) # [start:end] => where end is excluded
print(s['a':'d']) # [start:end] => end is inclusive

a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [98]:
# unique(), nunique(),s.max(),s.min().s.mean(),s.astype()

In [99]:
s = pd.Series(range(1,10))
s.astype(float)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
dtype: float64

#### Operations on series 

In [100]:
s1 = pd.Series(range(1,10))
s2 = pd.Series(range(1,10))

In [101]:
s1 + s2

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [102]:
s1 * 2

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [103]:
s1 ** 2

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int64

In [104]:
s1 * s2

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int64

In [105]:
s1/4

0    0.25
1    0.50
2    0.75
3    1.00
4    1.25
5    1.50
6    1.75
7    2.00
8    2.25
dtype: float64

In [106]:
s1//4

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    2
8    2
dtype: int64

In [107]:
s1%2

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
8    1
dtype: int64

In [108]:
var1 = 4
var2 = 5

In [109]:
var1 > var2

False

In [110]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [111]:
s2

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [112]:
s1 >= s2

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
dtype: bool

In [113]:
s1 > 5

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [114]:
s1[0] = 50

In [115]:
s1

0    50
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
dtype: int64

### DataFrame

In [116]:
print(type(pd.DataFrame()))
pd.DataFrame()

<class 'pandas.core.frame.DataFrame'>


Empty DataFrame
Columns: []
Index: []

In [117]:
df = pd.DataFrame(data = range(1,10))
df

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [118]:
df = pd.DataFrame(data = range(1,10), columns=['col1'])
df

col1
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9

In [119]:
df = pd.DataFrame(data = range(1,10), columns=['col1'], index = list('abcdefghi'))
df

col1
a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9

In [120]:
df = pd.DataFrame(data = [[1,2],[4,5],[6,7],[7,9]])
df

0  1
0  1  2
1  4  5
2  6  7
3  7  9

In [121]:
df = pd.DataFrame(data = [[1,2],[4,5],[6,7],[7,9]], columns=['col1','col2'])
df

col1  col2
0     1     2
1     4     5
2     6     7
3     7     9

In [122]:
df = pd.DataFrame(data = [[1,2],[4,5],[6,7],[7,9,6]], columns=['col1','col2','col3'])
df

col1  col2  col3
0     1     2   NaN
1     4     5   NaN
2     6     7   NaN
3     7     9   6.0

In [123]:
## NaN -> number a number => represents missing values
### NaN is float type. That is why 6 is converted as float

In [124]:
df = pd.DataFrame(data = [[1,2],[4,5],[6,7,'s'],[7,9,6]], columns=['col1','col2','col3'])
df

col1  col2  col3
0     1     2  None
1     4     5  None
2     6     7     s
3     7     9     6

In [125]:
# None (object) => represents missing values

In [126]:
## using data = dictionary
df = pd.DataFrame(data ={'a':[1,2,3],'b':[4,5,6],'c':[5,6,7]})
df

a  b  c
0  1  4  5
1  2  5  6
2  3  6  7

In [127]:
# ## using data = dictionary
# df = pd.DataFrame(data ={'a':[1,2,3],'b':[4,5,6],'c':[5,6]}) # error
# df

In [128]:
## using data = dictionary
df = pd.DataFrame(data ={'a':[1,2,3],'b':[4,5,'Na'],'c':[5,6,7]})
df

a   b  c
0  1   4  5
1  2   5  6
2  3  Na  7

In [129]:
## using data = series
df = pd.DataFrame(data = pd.Series({'a':[1,2,3],'b':[4,5,6],'c':[5,6,7]}))
df

0
a  [1, 2, 3]
b  [4, 5, 6]
c  [5, 6, 7]

In [130]:
## using data = series
df = pd.DataFrame(data = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[5,6,7]}))
df

a  b  c
0  1  4  5
1  2  5  6
2  3  6  7

### reading from external sources

In [131]:
# df = pd.read_csv()

In [132]:
# df

In [133]:
# df.to_csv('filename')